Friendship v2
Alexoid1/ror-social-scaffold pull request #3
Opened 2020-10-08 20:50 UTC by Alexoid1

Table friendship with user_id, friend_id and confirmed columns that gives a boleean value if there is friendship or not

2020-10-08 21:52 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Hi @Alexoid1 :clap: :clap:
#### Good job so far. You need to implement some missing requirements. Check the requirements :point_down:

- **_Enable linter for this repo_**

- **_Follow the Git flow as mentioned in the project requirement_**

- **_when friendship is confirmed, an additional row with reversed user-friend pair should be created_**

- **_PostsController#index should displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)). Right now this is showing all the users(friends or not) post_**

### Optional:
  **_You can read about `n+1` and make sure there are no `n + 1` queries in index views [Recommended article](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5)._**


#### _Reviewed by Temitayo Adeleke_

2020-10-08 21:52 UTC, lekegitrepo commented on .rubocop.yml
> +  Max: 180
- **_Do not modify any of the linter files. Please, restore the original value that was modified_**

2020-10-09 15:56 UTC, Alexoid1 commented on .rubocop.yml
> +  Max: 180
friend = Friendship.where(user_id: @friendship.friend_id)
    friend.find_by(friend_id: @friendship.user_id).update(confirmed: true)
that is the reversed user_friend a crerate another column in the same time that confirmed the friendship check the code the method is there do the same the only thing is that dont have that name of reversed friendship

2020-10-12 17:15 UTC, Alexoid1 commented on .rubocop.yml
> +  Max: 180
also in the model i dont call it reverse_frienships i just call it friends

has_many :friends, foreign_key: 'friend_id', class_name: 'Friendship'

i think  to call it reverse_friendship is no  mandatory or I'm wrong???

2020-10-12 17:15 UTC, closed without merging